model_name:
  value: "B"
dataset:
  value: "wave.nonlinear"
num_trajectories:
  value: 8000
batch_size:
  value: 8
num_epochs:
  value: 70
lr:
  value: 0.0001
lr_embedding_recovery:
  value: 0.001
weight_decay:
  value: 0.0001
max_grad_norm:
  value: 1.0
lr_scheduler:
  value: "cosine"
warmup_ratio:
  value: 0.1
early_stopping_patience:
  value: 10
